spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.100.188.255:3306/mybatis-debug
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml



